export const mockAgreements = [
  {
    id: "1",
    name: "Trade and Investment Framework Agreement",
    country: "jp",
    status: "in_progress",
    latestUpdate: "Negotiation phase 2 completed. Awaiting legal review.",
    updatedAt: "2024-03-15",
    description: "Framework agreement to promote trade and investment between the countries",
    startDate: "2023-10-01",
    endDate: "2025-10-01",
    type: "Trade",
    updates: [],
  },
  {
    id: "2",
    name: "Mutual Defense Cooperation Agreement",
    country: "gb",
    status: "completed",
    latestUpdate: "Agreement signed by both parties and ratified.",
    updatedAt: "2024-02-20",
    description: "Agreement on defense cooperation and joint military exercises",
    startDate: "2024-01-15",
    endDate: "2029-01-15",
    type: "Defense",
    updates: [],
  },
  {
    id: "3",
    name: "Cultural Exchange Program",
    country: "fr",
    status: "in_progress",
    latestUpdate: "Draft agreement under review by cultural ministry.",
    updatedAt: "2024-03-10",
    description: "Program for cultural exchange including arts, education, and heritage",
    startDate: "2024-06-01",
    endDate: "2026-06-01",
    type: "Cultural",
    updates: [],
  },
  {
    id: "4",
    name: "Science and Technology Cooperation",
    country: "de",
    status: "planned",
    latestUpdate: "Initial planning meeting scheduled for next month.",
    updatedAt: "2024-03-05",
    description: "Cooperation in research and development of new technologies",
    type: "Science",
    updates: [],
  },
  {
    id: "5",
    name: "Agricultural Trade Agreement",
    country: "br",
    status: "in_progress",
    latestUpdate: "Negotiations ongoing regarding tariff reductions.",
    updatedAt: "2024-03-18",
    description: "Agreement to reduce tariffs on agricultural products",
    startDate: "2023-12-01",
    type: "Trade",
    updates: [],
  },
  {
    id: "6",
    name: "Visa Waiver Program",
    country: "au",
    status: "completed",
    latestUpdate: "Program implemented successfully.",
    updatedAt: "2024-01-10",
    description: "Program allowing visa-free travel between countries for short stays",
    startDate: "2024-01-01",
    endDate: "2029-01-01",
    type: "Immigration",
    updates: [],
  },
  {
    id: "7",
    name: "Environmental Protection Cooperation",
    country: "ca",
    status: "in_progress",
    latestUpdate: "Working groups established for key environmental areas.",
    updatedAt: "2024-02-28",
    description: "Joint efforts to address climate change and environmental protection",
    startDate: "2024-02-01",
    endDate: "2026-02-01",
    type: "Environment",
    updates: [],
  },
  {
    id: "8",
    name: "Double Taxation Avoidance Agreement",
    country: "in",
    status: "expired",
    latestUpdate: "Agreement expired. Renewal discussions to begin next quarter.",
    updatedAt: "2024-01-05",
    description: "Agreement to prevent double taxation of income",
    startDate: "2019-01-01",
    endDate: "2024-01-01",
    type: "Taxation",
    updates: [],
  },
  {
    id: "9",
    name: "Cybersecurity Cooperation Framework",
    country: "us",
    status: "planned",
    latestUpdate: "Initial draft prepared by cybersecurity team.",
    updatedAt: "2024-03-20",
    description: "Framework for cooperation on cybersecurity threats and defense",
    type: "Security",
    updates: [],
  },
  {
    id: "10",
    name: "Educational Exchange Program",
    country: "cn",
    status: "cancelled",
    latestUpdate: "Program cancelled due to budget constraints.",
    updatedAt: "2024-02-15",
    description: "Program for exchange of students and faculty between universities",
    startDate: "2024-09-01",
    endDate: "2026-09-01",
    type: "Education",
    updates: [],
  },
]

