export const mockCountries = [
  {
    code: "us",
    name: "United States",
    region: "North America",
    capital: "Washington, D.C.",
  },
  {
    code: "gb",
    name: "United Kingdom",
    region: "Europe",
    capital: "London",
  },
  {
    code: "fr",
    name: "France",
    region: "Europe",
    capital: "Paris",
  },
  {
    code: "de",
    name: "Germany",
    region: "Europe",
    capital: "Berlin",
  },
  {
    code: "jp",
    name: "Japan",
    region: "Asia",
    capital: "Tokyo",
  },
  {
    code: "cn",
    name: "China",
    region: "Asia",
    capital: "Beijing",
  },
  {
    code: "in",
    name: "India",
    region: "Asia",
    capital: "New Delhi",
  },
  {
    code: "br",
    name: "Brazil",
    region: "South America",
    capital: "Brasília",
  },
  {
    code: "au",
    name: "Australia",
    region: "Oceania",
    capital: "Canberra",
  },
  {
    code: "za",
    name: "South Africa",
    region: "Africa",
    capital: "Pretoria",
  },
  {
    code: "sa",
    name: "Saudi Arabia",
    region: "Middle East",
    capital: "Riyadh",
  },
]

export const mockProfiles = [
  // United States
  {
    id: "1",
    country: "us",
    fullName: "Antony Blinken",
    position: "United States Secretary of State",
    type: "ambassador",
    education: "Harvard University (BA), Columbia Law School (JD)",
    overview: "Serving as the 71st United States Secretary of State since January 2021. Previously served as Deputy Secretary of State and Deputy National Security Advisor.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=AB",
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-03-20T14:30:00Z",
    lastModifiedBy: "Abdullah Al-Saud"
  },
  {
    id: "2",
    country: "us",
    fullName: "Victoria Nuland",
    position: "Deputy Secretary of State",
    type: "ambassador",
    education: "Brown University (BA), Diplomatic Academy of Moscow",
    overview: "Career diplomat serving as Deputy Secretary of State. Former Assistant Secretary of State for European and Eurasian Affairs.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=VN",
    createdAt: "2024-01-16T09:00:00Z",
    updatedAt: "2024-03-19T14:30:00Z",
    lastModifiedBy: "Mohammed Al-Qahtani"
  },
  {
    id: "3",
    country: "us",
    fullName: "Linda Thomas-Greenfield",
    position: "Ambassador to the United Nations",
    type: "ambassador",
    education: "Louisiana State University (BA), University of Wisconsin-Madison (MA)",
    overview: "Career diplomat serving as the United States Ambassador to the United Nations since 2021.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=LTG",
    createdAt: "2024-01-17T09:00:00Z",
    updatedAt: "2024-03-18T14:30:00Z",
    lastModifiedBy: "Fatima Al-Rashid"
  },
  {
    id: "4",
    country: "us",
    fullName: "Kurt Campbell",
    position: "Deputy Secretary of State",
    type: "ambassador",
    education: "Harvard College, Oxford University (PhD)",
    overview: "Serving as Deputy Secretary of State. Former Indo-Pacific Coordinator at the National Security Council.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=KC",
    createdAt: "2024-01-18T09:00:00Z",
    updatedAt: "2024-03-17T14:30:00Z",
    lastModifiedBy: "Ahmad Al-Ghamdi"
  },
  {
    id: "5",
    country: "us",
    fullName: "Wendy Sherman",
    position: "Former Deputy Secretary of State",
    type: "ambassador",
    education: "Boston University (BA), University of Maryland (MSW)",
    overview: "Distinguished diplomat who served as Deputy Secretary of State from 2021 to 2023.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=WS",
    createdAt: "2024-01-19T09:00:00Z",
    updatedAt: "2024-03-16T14:30:00Z",
    lastModifiedBy: "Noura Al-Otaibi"
  },

  // United Kingdom
  {
    id: "6",
    country: "gb",
    fullName: "David Cameron",
    position: "Secretary of State for Foreign Affairs",
    type: "ambassador",
    education: "Oxford University (BA)",
    overview: "Former Prime Minister of the United Kingdom, currently serving as Foreign Secretary since November 2023.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=DC",
    createdAt: "2024-02-01T10:15:00Z",
    updatedAt: "2024-03-18T16:45:00Z",
    lastModifiedBy: "Mohammed Al-Qahtani"
  },
  {
    id: "7",
    country: "gb",
    fullName: "Andrew Mitchell",
    position: "Minister of State for Development",
    type: "ambassador",
    education: "Cambridge University",
    overview: "Serving as Minister of State for Development in the Foreign Office since 2022.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=AM",
    createdAt: "2024-02-02T10:15:00Z",
    updatedAt: "2024-03-17T16:45:00Z",
    lastModifiedBy: "Sara Al-Zahrani"
  },
  {
    id: "8",
    country: "gb",
    fullName: "Karen Pierce",
    position: "Ambassador to the United States",
    type: "ambassador",
    education: "Cambridge University (BA), London School of Economics (MSc)",
    overview: "British Ambassador to the United States since 2020. Former Permanent Representative to the UN.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=KP",
    createdAt: "2024-02-03T10:15:00Z",
    updatedAt: "2024-03-16T16:45:00Z",
    lastModifiedBy: "Khalid Al-Harbi"
  },
  {
    id: "9",
    country: "gb",
    fullName: "Barbara Woodward",
    position: "Ambassador to the UN",
    type: "ambassador",
    education: "University of Reading, Yale University",
    overview: "British Permanent Representative to the United Nations since 2020.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=BW",
    createdAt: "2024-02-04T10:15:00Z",
    updatedAt: "2024-03-15T16:45:00Z",
    lastModifiedBy: "Rayan Al-Shamrani"
  },
  {
    id: "10",
    country: "gb",
    fullName: "Leo Docherty",
    position: "Minister for Europe",
    type: "non-ambassador",
    education: "University of London, Royal Military Academy Sandhurst",
    overview: "Serving as Minister of State for Europe since 2023.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=LD",
    createdAt: "2024-02-05T10:15:00Z",
    updatedAt: "2024-03-14T16:45:00Z",
    lastModifiedBy: "Layla Al-Maliki"
  },

  // France
  {
    id: "11",
    country: "fr",
    fullName: "Stéphane Séjourné",
    position: "Minister of Europe and Foreign Affairs",
    type: "ambassador",
    education: "Sciences Po Bordeaux",
    overview: "French politician serving as Minister of Europe and Foreign Affairs in the Attal government since January 2024.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=SS",
    createdAt: "2024-01-20T13:45:00Z",
    updatedAt: "2024-03-10T11:15:00Z",
    lastModifiedBy: "Ahmad Al-Ghamdi"
  },
  {
    id: "12",
    country: "fr",
    fullName: "Philippe Étienne",
    position: "Former Ambassador to the United States",
    type: "ambassador",
    education: "École normale supérieure, Sciences Po",
    overview: "Distinguished French diplomat who served as Ambassador to the United States from 2019 to 2023.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=PE",
    createdAt: "2024-01-21T13:45:00Z",
    updatedAt: "2024-03-09T11:15:00Z",
    lastModifiedBy: "Turki Al-Dossari"
  },
  {
    id: "13",
    country: "fr",
    fullName: "Catherine Colonna",
    position: "Former Minister of Foreign Affairs",
    type: "ambassador",
    education: "Sciences Po, ENA",
    overview: "French diplomat who served as Minister of Europe and Foreign Affairs from 2022 to 2024.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=CC",
    createdAt: "2024-01-22T13:45:00Z",
    updatedAt: "2024-03-08T11:15:00Z",
    lastModifiedBy: "Omar Al-Suwaidi"
  },
  {
    id: "14",
    country: "fr",
    fullName: "Nicolas de Rivière",
    position: "Ambassador to the UN",
    type: "ambassador",
    education: "Sciences Po, ENA",
    overview: "French Permanent Representative to the United Nations since 2019.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=NR",
    createdAt: "2024-01-23T13:45:00Z",
    updatedAt: "2024-03-07T11:15:00Z",
    lastModifiedBy: "Nasser Al-Mutairi"
  },
  {
    id: "15",
    country: "fr",
    fullName: "Jean-Yves Le Drian",
    position: "Former Minister of Foreign Affairs",
    type: "ambassador",
    education: "University of Rennes",
    overview: "French politician who served as Minister of Europe and Foreign Affairs from 2017 to 2022.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=JD",
    createdAt: "2024-01-24T13:45:00Z",
    updatedAt: "2024-03-06T11:15:00Z",
    lastModifiedBy: "Hana Al-Shehri"
  },

  // Germany
  {
    id: "16",
    country: "de",
    fullName: "Annalena Baerbock",
    position: "Federal Minister of Foreign Affairs",
    type: "ambassador",
    education: "London School of Economics (LLM), University of Hamburg (BA)",
    overview: "German politician serving as Federal Minister for Foreign Affairs since 2021. First woman to hold this position.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=AB",
    createdAt: "2024-02-15T08:30:00Z",
    updatedAt: "2024-03-05T15:40:00Z",
    lastModifiedBy: "Noura Al-Otaibi"
  },
  {
    id: "17",
    country: "de",
    fullName: "Emily Haber",
    position: "Former Ambassador to the United States",
    type: "ambassador",
    education: "University of Cologne, PhD in History",
    overview: "German diplomat who served as Ambassador to the United States from 2018 to 2023.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=EH",
    createdAt: "2024-02-16T08:30:00Z",
    updatedAt: "2024-03-04T15:40:00Z",
    lastModifiedBy: "Fahad Al-Thani"
  },
  {
    id: "18",
    country: "de",
    fullName: "Antje Leendertse",
    position: "Ambassador to the UN",
    type: "ambassador",
    education: "University of Göttingen",
    overview: "German Permanent Representative to the United Nations since 2021.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=AL",
    createdAt: "2024-02-17T08:30:00Z",
    updatedAt: "2024-03-03T15:40:00Z",
    lastModifiedBy: "Amira Al-Mansouri"
  },
  {
    id: "19",
    country: "de",
    fullName: "Tobias Lindner",
    position: "Minister of State at the Federal Foreign Office",
    type: "non-ambassador",
    education: "University of Karlsruhe, PhD in Economics",
    overview: "German politician serving as Minister of State at the Federal Foreign Office since 2021.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=TL",
    createdAt: "2024-02-18T08:30:00Z",
    updatedAt: "2024-03-02T15:40:00Z",
    lastModifiedBy: "Yazeed Al-Dhaheri"
  },
  {
    id: "20",
    country: "de",
    fullName: "Andreas Michaelis",
    position: "State Secretary of the Federal Foreign Office",
    type: "ambassador",
    education: "University of Oxford, University of Bonn",
    overview: "Career diplomat serving as State Secretary of the Federal Foreign Office.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=AM",
    createdAt: "2024-02-19T08:30:00Z",
    updatedAt: "2024-03-01T15:40:00Z",
    lastModifiedBy: "Zainab Al-Kuwaiti"
  },

  // Japan
  {
    id: "21",
    country: "jp",
    fullName: "Yoko Kamikawa",
    position: "Minister for Foreign Affairs",
    type: "ambassador",
    education: "Kyoto University, University of Pennsylvania (MA)",
    overview: "Japanese politician serving as Minister for Foreign Affairs since September 2023. Former Minister of Justice.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=YK",
    createdAt: "2023-11-05T14:20:00Z",
    updatedAt: "2024-03-01T10:30:00Z",
    lastModifiedBy: "Khalid Al-Harbi"
  },
  {
    id: "22",
    country: "jp",
    fullName: "Shigeo Yamada",
    position: "Vice Minister for Foreign Affairs",
    type: "ambassador",
    education: "University of Tokyo",
    overview: "Career diplomat serving as Vice Minister for Foreign Affairs.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=SY",
    createdAt: "2023-11-06T14:20:00Z",
    updatedAt: "2024-02-29T10:30:00Z",
    lastModifiedBy: "Abdullah Al-Saud"
  },
  {
    id: "23",
    country: "jp",
    fullName: "Koji Tomita",
    position: "Former Ambassador to the United States",
    type: "ambassador",
    education: "University of Tokyo",
    overview: "Japanese diplomat who served as Ambassador to the United States from 2021 to 2023.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=KT",
    createdAt: "2023-11-07T14:20:00Z",
    updatedAt: "2024-02-28T10:30:00Z",
    lastModifiedBy: "Mohammed Al-Qahtani"
  },
  {
    id: "24",
    country: "jp",
    fullName: "Kimihiro Ishikane",
    position: "Ambassador to the UN",
    type: "ambassador",
    education: "University of Tokyo, Stanford University",
    overview: "Japanese Permanent Representative to the United Nations since 2019.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=KI",
    createdAt: "2023-11-08T14:20:00Z",
    updatedAt: "2024-02-27T10:30:00Z",
    lastModifiedBy: "Fatima Al-Rashid"
  },
  {
    id: "25",
    country: "jp",
    fullName: "Yoshimasa Hayashi",
    position: "Former Minister for Foreign Affairs",
    type: "ambassador",
    education: "University of Tokyo, Harvard University (MPA)",
    overview: "Japanese politician who served as Minister for Foreign Affairs from 2021 to 2023.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=YH",
    createdAt: "2023-11-09T14:20:00Z",
    updatedAt: "2024-02-26T10:30:00Z",
    lastModifiedBy: "Ahmad Al-Ghamdi"
  },

  // China
  {
    id: "26",
    country: "cn",
    fullName: "Wang Yi",
    position: "Minister of Foreign Affairs",
    type: "ambassador",
    education: "Beijing International Studies University, China Foreign Affairs University",
    overview: "Chinese diplomat and politician serving as Minister of Foreign Affairs since 2023. Previously served in the same role from 2013 to 2022.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=WY",
    createdAt: "2024-01-10T16:15:00Z",
    updatedAt: "2024-02-28T13:25:00Z",
    lastModifiedBy: "Sara Al-Zahrani"
  },
  {
    id: "27",
    country: "cn",
    fullName: "Ma Zhaoxu",
    position: "Vice Minister of Foreign Affairs",
    type: "ambassador",
    education: "Beijing Foreign Studies University",
    overview: "Career diplomat serving as Vice Minister of Foreign Affairs since 2019.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=MZ",
    createdAt: "2024-01-11T16:15:00Z",
    updatedAt: "2024-02-27T13:25:00Z",
    lastModifiedBy: "Turki Al-Dossari"
  },
  {
    id: "28",
    country: "cn",
    fullName: "Xie Feng",
    position: "Ambassador to the United States",
    type: "ambassador",
    education: "China Foreign Affairs University",
    overview: "Chinese diplomat serving as Ambassador to the United States since 2023.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=XF",
    createdAt: "2024-01-12T16:15:00Z",
    updatedAt: "2024-02-26T13:25:00Z",
    lastModifiedBy: "Omar Al-Suwaidi"
  },
  {
    id: "29",
    country: "cn",
    fullName: "Zhang Jun",
    position: "Ambassador to the UN",
    type: "ambassador",
    education: "China Foreign Affairs University",
    overview: "Chinese Permanent Representative to the United Nations since 2019.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=ZJ",
    createdAt: "2024-01-13T16:15:00Z",
    updatedAt: "2024-02-25T13:25:00Z",
    lastModifiedBy: "Nasser Al-Mutairi"
  },
  {
    id: "30",
    country: "cn",
    fullName: "Qin Gang",
    position: "Former Minister of Foreign Affairs",
    type: "ambassador",
    education: "University of International Relations",
    overview: "Chinese diplomat who served as Minister of Foreign Affairs in 2023.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=QG",
    createdAt: "2024-01-14T16:15:00Z",
    updatedAt: "2024-02-24T13:25:00Z",
    lastModifiedBy: "Hana Al-Shehri"
  },

  // India
  {
    id: "31",
    country: "in",
    fullName: "Subrahmanyam Jaishankar",
    position: "Minister of External Affairs",
    type: "ambassador",
    education: "St. Stephen's College, Delhi, JNU (MA, MPhil, PhD)",
    overview: "Indian diplomat and politician serving as Minister of External Affairs since 2019. Former Foreign Secretary of India.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=SJ",
    createdAt: "2024-01-08T13:45:00Z",
    updatedAt: "2024-03-17T09:15:00Z",
    lastModifiedBy: "Rayan Al-Shamrani"
  },
  {
    id: "32",
    country: "in",
    fullName: "Vinay Mohan Kwatra",
    position: "Foreign Secretary",
    type: "ambassador",
    education: "University of Delhi",
    overview: "Indian Foreign Service officer serving as Foreign Secretary since 2022.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=VK",
    createdAt: "2024-01-09T13:45:00Z",
    updatedAt: "2024-03-16T09:15:00Z",
    lastModifiedBy: "Layla Al-Maliki"
  },
  {
    id: "33",
    country: "in",
    fullName: "Taranjit Singh Sandhu",
    position: "Former Ambassador to the United States",
    type: "ambassador",
    education: "St. Stephen's College, Delhi",
    overview: "Indian diplomat who served as Ambassador to the United States from 2020 to 2024.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=TS",
    createdAt: "2024-01-10T13:45:00Z",
    updatedAt: "2024-03-15T09:15:00Z",
    lastModifiedBy: "Khalid Al-Harbi"
  },
  {
    id: "34",
    country: "in",
    fullName: "Ruchira Kamboj",
    position: "Ambassador to the UN",
    type: "ambassador",
    education: "University of Delhi",
    overview: "Indian Permanent Representative to the United Nations since 2022.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=RK",
    createdAt: "2024-01-11T13:45:00Z",
    updatedAt: "2024-03-14T09:15:00Z",
    lastModifiedBy: "Sara Al-Zahrani"
  },
  {
    id: "35",
    country: "in",
    fullName: "Harsh Vardhan Shringla",
    position: "Former Foreign Secretary",
    type: "ambassador",
    education: "St. Stephen's College, Delhi",
    overview: "Indian diplomat who served as Foreign Secretary from 2020 to 2022.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=HS",
    createdAt: "2024-01-12T13:45:00Z",
    updatedAt: "2024-03-13T09:15:00Z",
    lastModifiedBy: "Turki Al-Dossari"
  },

  // Australia
  {
    id: "36",
    country: "au",
    fullName: "Penny Wong",
    position: "Minister for Foreign Affairs",
    type: "ambassador",
    education: "University of Adelaide (LLB), University of South Australia (BA)",
    overview: "Australian politician serving as Minister for Foreign Affairs since 2022. First Asian-born member of an Australian cabinet.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=PW",
    createdAt: "2024-02-01T09:20:00Z",
    updatedAt: "2024-03-14T13:50:00Z",
    lastModifiedBy: "Layla Al-Maliki"
  },
  {
    id: "37",
    country: "au",
    fullName: "Jan Adams",
    position: "Secretary of the Department of Foreign Affairs and Trade",
    type: "ambassador",
    education: "University of Melbourne, Australian National University",
    overview: "Career diplomat serving as Secretary of DFAT since 2022.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=JA",
    createdAt: "2024-02-02T09:20:00Z",
    updatedAt: "2024-03-13T13:50:00Z",
    lastModifiedBy: "Omar Al-Suwaidi"
  },
  {
    id: "38",
    country: "au",
    fullName: "Kevin Rudd",
    position: "Ambassador to the United States",
    type: "ambassador",
    education: "Australian National University, Oxford University (PhD)",
    overview: "Former Prime Minister of Australia, currently serving as Ambassador to the United States since 2023.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=KR",
    createdAt: "2024-02-03T09:20:00Z",
    updatedAt: "2024-03-12T13:50:00Z",
    lastModifiedBy: "Nasser Al-Mutairi"
  },
  {
    id: "39",
    country: "au",
    fullName: "Mitch Fifield",
    position: "Ambassador to the UN",
    type: "ambassador",
    education: "University of Sydney",
    overview: "Australian Permanent Representative to the United Nations since 2019.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=MF",
    createdAt: "2024-02-04T09:20:00Z",
    updatedAt: "2024-03-11T13:50:00Z",
    lastModifiedBy: "Hana Al-Shehri"
  },
  {
    id: "40",
    country: "au",
    fullName: "Tim Watts",
    position: "Assistant Minister for Foreign Affairs",
    type: "non-ambassador",
    education: "University of Melbourne, London School of Economics",
    overview: "Australian politician serving as Assistant Minister for Foreign Affairs since 2022.",
    imageUrl: "/placeholder.svg?height=200&width=200&text=TW",
    createdAt: "2024-02-05T09:20:00Z",
    updatedAt: "2024-03-10T13:50:00Z",
    lastModifiedBy: "Fahad Al-Thani"
  }
]

