// Define the action item type
export interface ActionItem {
  id: string
  country: string
  profileId: string
  date: string
  source: string
  theme: string
  industry: string
  actionItem: string
  updates: string
  entities: string
  entitiesOther: string
  status: "not_started" | "in_progress" | "done"
  owner: string
  dueDate: string
}

// Mock data for action items
export const mockActionItems: ActionItem[] = [
  // United States (us)
  {
    id: "1",
    country: "us",
    profileId: "1", // Antony Blinken
    date: "2024-02-15",
    source: "Bilateral Meeting",
    theme: "Trade",
    industry: "Technology",
    actionItem: "Establish joint working group on technology standards",
    updates: "Initial contacts made with US Trade Representative",
    entities: "Ministry of Commerce",
    entitiesOther: "US Department of Commerce",
    status: "in_progress",
    owner: "John Smith",
    dueDate: "2024-06-30",
  },
  {
    id: "2",
    country: "us",
    profileId: "2", // Victoria Nuland
    date: "2024-01-22",
    source: "Summit",
    theme: "Investment",
    industry: "Finance",
    actionItem: "Develop framework for US investment in financial sector",
    updates: "Initial proposal drafted",
    entities: "Investment Authority",
    entitiesOther: "US Treasury Department",
    status: "not_started",
    owner: "Sarah Johnson",
    dueDate: "2024-07-15",
  },
  {
    id: "3",
    country: "us",
    profileId: "3", // Linda Thomas-Greenfield
    date: "2024-03-05",
    source: "Conference",
    theme: "Human Capital",
    industry: "Education",
    actionItem: "Establish joint education exchange program with US universities",
    updates: "Initial discussions with education ministry",
    entities: "Ministry of Education",
    entitiesOther: "US Department of Education",
    status: "not_started",
    owner: "Michael Brown",
    dueDate: "2024-08-20",
  },
  {
    id: "4",
    country: "us",
    profileId: "4", // Kurt Campbell
    date: "2024-02-10",
    source: "Delegation Visit",
    theme: "Knowledge Sharing",
    industry: "Renewable Energy",
    actionItem: "Implement knowledge exchange program on renewable energy technologies",
    updates: "Program outline drafted",
    entities: "Research Institute",
    entitiesOther: "US Department of Energy",
    status: "in_progress",
    owner: "Emily Davis",
    dueDate: "2024-05-30",
  },
  
  // United Kingdom (gb)
  {
    id: "5",
    country: "gb",
    profileId: "6", // David Cameron
    date: "2024-03-05",
    source: "Summit",
    theme: "Human Capital",
    industry: "Education",
    actionItem: "Establish student exchange program with UK universities",
    updates: "MOU drafted and under review",
    entities: "Ministry of Education",
    entitiesOther: "British Council",
    status: "in_progress",
    owner: "Michael Brown",
    dueDate: "2024-05-30",
  },
  {
    id: "6",
    country: "gb",
    profileId: "7", // Andrew Mitchell
    date: "2024-01-18",
    source: "Trade Mission",
    theme: "Trade",
    industry: "Financial Services",
    actionItem: "Develop framework for financial services cooperation post-Brexit",
    updates: "Working group established",
    entities: "Finance Ministry",
    entitiesOther: "UK Treasury",
    status: "in_progress",
    owner: "James Wilson",
    dueDate: "2024-07-10",
  },
  {
    id: "7",
    country: "gb",
    profileId: "8", // Karen Pierce
    date: "2024-02-12",
    source: "Conference",
    theme: "Investment",
    industry: "Technology",
    actionItem: "Attract UK tech investment in local startup ecosystem",
    updates: "Initial proposal presented to UK Trade & Investment",
    entities: "Investment Authority",
    entitiesOther: "UK Department for Business and Trade",
    status: "not_started",
    owner: "Robert Thompson",
    dueDate: "2024-09-15",
  },
  {
    id: "8",
    country: "gb",
    profileId: "9", // Barbara Woodward
    date: "2024-03-01",
    source: "Bilateral Meeting",
    theme: "Knowledge Sharing",
    industry: "Healthcare",
    actionItem: "Develop joint research program on healthcare innovations",
    updates: "Research priorities identified",
    entities: "Health Research Institute",
    entitiesOther: "UK National Health Service",
    status: "in_progress",
    owner: "Jennifer Lee",
    dueDate: "2024-06-20",
  },
  
  // France (fr)
  {
    id: "9",
    country: "fr",
    profileId: "11", // Stéphane Séjourné
    date: "2024-03-12",
    source: "Bilateral Meeting",
    theme: "Other",
    industry: "Tourism",
    actionItem: "Develop joint tourism promotion campaign",
    updates: "Campaign concept approved",
    entities: "Tourism Board",
    entitiesOther: "Atout France",
    status: "in_progress",
    dueDate: "2024-06-15",
    owner: "Jennifer Lee",
  },
  {
    id: "10",
    country: "fr",
    profileId: "11", // Stéphane Séjourné
    date: "2024-01-25",
    source: "Trade Mission",
    theme: "Trade",
    industry: "Agriculture",
    actionItem: "Enhance agricultural exports to French market",
    updates: "Initial market analysis completed",
    entities: "Ministry of Agriculture",
    entitiesOther: "French Ministry of Agriculture",
    status: "not_started",
    owner: "Paul Martin",
    dueDate: "2024-08-05",
  },
  {
    id: "11",
    country: "fr",
    profileId: "11", // Stéphane Séjourné
    date: "2024-02-08",
    source: "Conference",
    theme: "Knowledge Sharing",
    industry: "Renewable Energy",
    actionItem: "Develop joint research program on solar energy technology",
    updates: "Initial proposal submitted",
    entities: "Energy Research Institute",
    entitiesOther: "French National Centre for Scientific Research",
    status: "in_progress",
    owner: "Robert Green",
    dueDate: "2024-07-20",
  },
  {
    id: "12",
    country: "fr",
    profileId: "11", // Stéphane Séjourné
    date: "2024-03-02",
    source: "Forum",
    theme: "Investment",
    industry: "Technology",
    actionItem: "Attract French tech investments in digital economy",
    updates: "Investment prospectus prepared",
    entities: "Digital Economy Authority",
    entitiesOther: "Business France",
    status: "not_started",
    owner: "Marie Dubois",
    dueDate: "2024-09-30",
  },
  
  // Germany (de)
  {
    id: "13",
    country: "de",
    profileId: "20", // Andreas Michaelis
    date: "2024-02-28",
    source: "Conference",
    theme: "Knowledge Sharing",
    industry: "Renewable Energy",
    actionItem: "Collaborate on renewable energy research projects",
    updates: "Initial research proposal completed",
    entities: "Research Institute",
    entitiesOther: "German Energy Agency",
    status: "done",
    dueDate: "2024-04-15",
    owner: "Emily Davis",
  },
  {
    id: "14",
    country: "de",
    profileId: "20", // Andreas Michaelis
    date: "2024-01-15",
    source: "Trade Mission",
    theme: "Trade",
    industry: "Automotive",
    actionItem: "Establish supply chain partnership for electric vehicle components",
    updates: "Initial meetings held with German manufacturers",
    entities: "Trade Ministry",
    entitiesOther: "German Automotive Industry Association",
    status: "in_progress",
    owner: "Thomas Schmidt",
    dueDate: "2024-07-25",
  },
  {
    id: "15",
    country: "de",
    profileId: "20", // Andreas Michaelis
    date: "2024-03-10",
    source: "Summit",
    theme: "Investment",
    industry: "Manufacturing",
    actionItem: "Attract German manufacturing investment in industrial zones",
    updates: "Site visits scheduled with German delegation",
    entities: "Investment Authority",
    entitiesOther: "German Chamber of Commerce",
    status: "not_started",
    owner: "Hans Mueller",
    dueDate: "2024-08-10",
  },
  {
    id: "16",
    country: "de",
    profileId: "20", // Andreas Michaelis
    date: "2024-02-05",
    source: "Bilateral Meeting",
    theme: "Human Capital",
    industry: "Vocational Training",
    actionItem: "Develop vocational training partnership with German institutes",
    updates: "Training needs assessment completed",
    entities: "Ministry of Labor",
    entitiesOther: "German Federal Institute for Vocational Education and Training",
    status: "in_progress",
    owner: "Anna Fischer",
    dueDate: "2024-06-15",
  },
  
  // Japan (jp)
  {
    id: "17",
    country: "jp",
    profileId: "21", // Yoko Kamikawa
    date: "2024-01-20",
    source: "Conference",
    theme: "Investment",
    industry: "Manufacturing",
    actionItem: "Facilitate investment in automotive manufacturing",
    updates: "",
    entities: "Investment Authority",
    entitiesOther: "Japan External Trade Organization",
    status: "not_started",
    owner: "Sarah Johnson",
    dueDate: "2024-07-15",
  },
  {
    id: "18",
    country: "jp",
    profileId: "22", // Shigeo Yamada
    date: "2024-03-05",
    source: "Trade Mission",
    theme: "Trade",
    industry: "Electronics",
    actionItem: "Increase electronics component exports to Japan",
    updates: "Market access negotiations in progress",
    entities: "Trade Ministry",
    entitiesOther: "Japan Electronics and Information Technology Industries Association",
    status: "in_progress",
    owner: "Kenji Tanaka",
    dueDate: "2024-06-30",
  },
  {
    id: "19",
    country: "jp",
    profileId: "23", // Koji Tomita
    date: "2024-02-18",
    source: "Summit",
    theme: "Human Capital",
    industry: "Technology",
    actionItem: "Develop technical training program with Japanese experts",
    updates: "Program outline drafted",
    entities: "Technical Education Board",
    entitiesOther: "Japan International Cooperation Agency",
    status: "in_progress",
    owner: "Kevin Yamamoto",
    dueDate: "2024-08-20",
  },
  {
    id: "20",
    country: "jp",
    profileId: "24", // Kimihiro Ishikane
    date: "2024-01-30",
    source: "Forum",
    theme: "Knowledge Sharing",
    industry: "Robotics",
    actionItem: "Establish knowledge exchange on industrial robotics",
    updates: "Technical exchange framework developed",
    entities: "Technology Institute",
    entitiesOther: "Japan Robot Association",
    status: "done",
    owner: "Akira Nakamura",
    dueDate: "2024-04-30",
  },
  
  // China (cn)
  {
    id: "21",
    country: "cn",
    profileId: "26", // Wang Yi
    date: "2024-01-10",
    source: "Delegation Visit",
    theme: "Trade",
    industry: "Agriculture",
    actionItem: "Increase agricultural exports to China",
    updates: "",
    entities: "Ministry of Agriculture",
    entitiesOther: "China Chamber of Commerce",
    status: "not_started",
    dueDate: "2024-08-01",
    owner: "Robert Wilson",
  },
  {
    id: "22",
    country: "cn",
    profileId: "27", // Ma Zhaoxu
    date: "2024-02-25",
    source: "Bilateral Meeting",
    theme: "Investment",
    industry: "Infrastructure",
    actionItem: "Secure Chinese investment for port development project",
    updates: "Initial proposal presented to Chinese delegation",
    entities: "Infrastructure Development Authority",
    entitiesOther: "China Development Bank",
    status: "in_progress",
    dueDate: "2024-07-15",
    owner: "Li Wei",
  },
  {
    id: "23",
    country: "cn",
    profileId: "28", // Xie Feng
    date: "2024-03-08",
    source: "Conference",
    theme: "Knowledge Sharing",
    industry: "Digital Technology",
    actionItem: "Develop digital technology knowledge exchange program",
    updates: "Framework agreement drafted",
    entities: "Technology Innovation Center",
    entitiesOther: "China Academy of Information and Communications Technology",
    status: "in_progress",
    dueDate: "2024-06-15",
    owner: "Zhang Wei",
  },
  {
    id: "24",
    country: "cn",
    profileId: "29", // Zhang Jun
    date: "2024-02-03",
    source: "Forum",
    theme: "Human Capital",
    industry: "Education",
    actionItem: "Establish educational exchange with Chinese universities",
    updates: "Partner universities identified",
    entities: "Higher Education Commission",
    entitiesOther: "China Education Association for International Exchange",
    status: "not_started",
    dueDate: "2024-09-01",
    owner: "Liu Mei",
  },
  
  // India (in)
  {
    id: "25",
    country: "in",
    profileId: "31", // Subrahmanyam Jaishankar
    date: "2024-02-05",
    source: "Summit",
    theme: "Investment",
    industry: "Technology",
    actionItem: "Attract Indian IT companies to establish local offices",
    updates: "Three companies expressed interest",
    entities: "Investment Authority",
    entitiesOther: "NASSCOM",
    status: "in_progress",
    dueDate: "2024-07-30",
    owner: "David Chen",
  },
  {
    id: "26",
    country: "in",
    profileId: "31", // Subrahmanyam Jaishankar
    date: "2024-01-18",
    source: "Trade Mission",
    theme: "Trade",
    industry: "Pharmaceuticals",
    actionItem: "Enhance pharmaceutical trade with India",
    updates: "Regulatory harmonization discussions initiated",
    entities: "Pharmaceutical Regulatory Authority",
    entitiesOther: "Indian Pharmaceutical Alliance",
    status: "not_started",
    dueDate: "2024-08-15",
    owner: "Rajan Patel",
  },
  {
    id: "27",
    country: "in",
    profileId: "31", // Subrahmanyam Jaishankar
    date: "2024-03-12",
    source: "Conference",
    theme: "Knowledge Sharing",
    industry: "Agriculture",
    actionItem: "Develop knowledge sharing on agricultural technologies",
    updates: "Priority areas identified",
    entities: "Agricultural Research Institute",
    entitiesOther: "Indian Council of Agricultural Research",
    status: "in_progress",
    dueDate: "2024-06-20",
    owner: "Sanjay Kumar",
  },
  {
    id: "28",
    country: "in",
    profileId: "31", // Subrahmanyam Jaishankar
    date: "2024-02-22",
    source: "Bilateral Meeting",
    theme: "Human Capital",
    industry: "Healthcare",
    actionItem: "Establish medical professional exchange program",
    updates: "Program framework developed",
    entities: "Ministry of Health",
    entitiesOther: "National Medical Commission of India",
    status: "in_progress",
    dueDate: "2024-07-10",
    owner: "Priya Sharma",
  },
  
  // Brazil (br)
  {
    id: "29",
    country: "br",
    profileId: "10", // Carlos Silva (using an existing profile ID)
    date: "2024-01-25",
    source: "Trade Mission",
    theme: "Trade",
    industry: "Manufacturing",
    actionItem: "Reduce tariffs on manufactured goods",
    updates: "Negotiations ongoing",
    entities: "Ministry of Commerce",
    entitiesOther: "Brazilian Ministry of Economy",
    status: "in_progress",
    dueDate: "2024-09-15",
    owner: "Maria Rodriguez",
  },
  {
    id: "30",
    country: "br",
    profileId: "10", // Carlos Silva
    date: "2024-02-15",
    source: "Conference",
    theme: "Investment",
    industry: "Renewable Energy",
    actionItem: "Attract Brazilian investment in solar energy projects",
    updates: "Initial discussions with Brazilian investors",
    entities: "Renewable Energy Authority",
    entitiesOther: "Brazilian Association of Clean Energy",
    status: "not_started",
    dueDate: "2024-07-30",
    owner: "Eduardo Santos",
  },
  {
    id: "31",
    country: "br",
    profileId: "10", // Carlos Silva
    date: "2024-03-05",
    source: "Forum",
    theme: "Human Capital",
    industry: "Agriculture",
    actionItem: "Develop agricultural technology training program with Brazilian experts",
    updates: "Initial curriculum drafted",
    entities: "Agricultural Training Institute",
    entitiesOther: "Brazilian Agricultural Research Corporation",
    status: "in_progress",
    dueDate: "2024-08-15",
    owner: "Carlos Mendes",
  },
  {
    id: "32",
    country: "br",
    profileId: "10", // Carlos Silva
    date: "2024-01-30",
    source: "Bilateral Meeting",
    theme: "Knowledge Sharing",
    industry: "Forestry",
    actionItem: "Establish knowledge exchange on sustainable forestry practices",
    updates: "Exchange protocol drafted",
    entities: "Forestry Department",
    entitiesOther: "Brazilian Forest Service",
    status: "done",
    dueDate: "2024-04-20",
    owner: "Ana Costa",
  },
  
  // Australia (au)
  {
    id: "33",
    country: "au",
    profileId: "36", // Penny Wong
    date: "2024-03-18",
    source: "Forum",
    theme: "Human Capital",
    industry: "Education",
    actionItem: "Develop joint research initiatives with Australian universities",
    updates: "",
    entities: "Ministry of Education",
    entitiesOther: "Universities Australia",
    status: "not_started",
    dueDate: "2024-08-30",
    owner: "James Wilson",
  },
  {
    id: "34",
    country: "au",
    profileId: "37", // Jan Adams
    date: "2024-01-22",
    source: "Trade Mission",
    theme: "Trade",
    industry: "Mining",
    actionItem: "Establish strategic minerals trade framework",
    updates: "Priority minerals identified",
    entities: "Mineral Resources Authority",
    entitiesOther: "Minerals Council of Australia",
    status: "in_progress",
    dueDate: "2024-07-15",
    owner: "Andrew Johnson",
  },
  {
    id: "35",
    country: "au",
    profileId: "38", // Kevin Rudd
    date: "2024-02-10",
    source: "Conference",
    theme: "Knowledge Sharing",
    industry: "Water Management",
    actionItem: "Develop water conservation knowledge exchange program",
    updates: "Program structure drafted",
    entities: "Water Resources Authority",
    entitiesOther: "Australian Water Association",
    status: "in_progress",
    dueDate: "2024-06-30",
    owner: "Emma Wilson",
  },
  {
    id: "36",
    country: "au",
    profileId: "36", // Penny Wong
    date: "2024-03-02",
    source: "Bilateral Meeting",
    theme: "Investment",
    industry: "Renewable Energy",
    actionItem: "Secure Australian investment in green hydrogen projects",
    updates: "Investment proposal drafted",
    entities: "Energy Investment Authority",
    entitiesOther: "Australian Renewable Energy Agency",
    status: "not_started",
    dueDate: "2024-09-15",
    owner: "Michael Thompson",
  },
  
  // South Africa (za)
  {
    id: "37",
    country: "za",
    profileId: "1", // Using a stand-in profile ID
    date: "2024-01-15",
    source: "Conference",
    theme: "Investment",
    industry: "Mining",
    actionItem: "Attract South African mining investment",
    updates: "Investment incentives package prepared",
    entities: "Mining Investment Authority",
    entitiesOther: "Minerals Council South Africa",
    status: "in_progress",
    dueDate: "2024-07-20",
    owner: "Nelson Mandela",
  },
  {
    id: "38",
    country: "za",
    profileId: "1", // Using a stand-in profile ID
    date: "2024-02-20",
    source: "Trade Mission",
    theme: "Trade",
    industry: "Agriculture",
    actionItem: "Enhance agricultural exports to South African market",
    updates: "Market access negotiations initiated",
    entities: "Ministry of Agriculture",
    entitiesOther: "South African Department of Trade and Industry",
    status: "not_started",
    dueDate: "2024-08-15",
    owner: "Thabo Mbeki",
  },
  {
    id: "39",
    country: "za",
    profileId: "1", // Using a stand-in profile ID
    date: "2024-03-05",
    source: "Summit",
    theme: "Human Capital",
    industry: "Healthcare",
    actionItem: "Develop healthcare professional exchange program",
    updates: "Program outline completed",
    entities: "Ministry of Health",
    entitiesOther: "South African Medical Association",
    status: "in_progress",
    dueDate: "2024-06-25",
    owner: "Cyril Ramaphosa",
  },
  {
    id: "40",
    country: "za",
    profileId: "1", // Using a stand-in profile ID
    date: "2024-02-08",
    source: "Forum",
    theme: "Knowledge Sharing",
    industry: "Renewable Energy",
    actionItem: "Establish knowledge exchange on solar energy technologies",
    updates: "Exchange framework developed",
    entities: "Renewable Energy Research Center",
    entitiesOther: "South African National Energy Development Institute",
    status: "done",
    dueDate: "2024-04-30",
    owner: "Desmond Tutu",
  },
  
  // Saudi Arabia (sa)
  {
    id: "41",
    country: "sa",
    profileId: "1", // Using a stand-in profile ID
    date: "2024-02-10",
    source: "Conference",
    theme: "Investment",
    industry: "Energy",
    actionItem: "Secure Saudi investment in energy infrastructure",
    updates: "Initial proposal presented",
    entities: "Energy Ministry",
    entitiesOther: "Saudi Ministry of Energy",
    status: "done",
    dueDate: "2024-03-30",
    owner: "Lisa Thompson",
  },
  {
    id: "42",
    country: "sa",
    profileId: "1", // Using a stand-in profile ID
    date: "2024-01-25",
    source: "Trade Mission",
    theme: "Trade",
    industry: "Manufacturing",
    actionItem: "Increase exports of manufactured goods to Saudi market",
    updates: "Market analysis completed",
    entities: "Export Promotion Bureau",
    entitiesOther: "Saudi Chambers of Commerce",
    status: "in_progress",
    dueDate: "2024-07-15",
    owner: "Mohammed Al-Saud",
  },
  {
    id: "43",
    country: "sa",
    profileId: "1", // Using a stand-in profile ID
    date: "2024-03-15",
    source: "Bilateral Meeting",
    theme: "Human Capital",
    industry: "Education",
    actionItem: "Develop educational exchange with Saudi universities",
    updates: "Partner institutions identified",
    entities: "Higher Education Commission",
    entitiesOther: "Saudi Ministry of Education",
    status: "not_started",
    dueDate: "2024-08-20",
    owner: "Abdullah Al-Rahman",
  },
  {
    id: "44",
    country: "sa",
    profileId: "1", // Using a stand-in profile ID
    date: "2024-02-28",
    source: "Forum",
    theme: "Knowledge Sharing",
    industry: "Water Management",
    actionItem: "Establish knowledge exchange on water desalination technologies",
    updates: "Technical parameters defined",
    entities: "Water Resources Authority",
    entitiesOther: "Saline Water Conversion Corporation",
    status: "in_progress",
    dueDate: "2024-06-15",
    owner: "Fatima Al-Saud",
  },
  
  // Canada (ca)
  {
    id: "45",
    country: "ca",
    profileId: "13", // Michael Thompson
    date: "2024-02-10",
    source: "Conference",
    theme: "Investment",
    industry: "Energy",
    actionItem: "Secure Canadian investment in energy infrastructure",
    updates: "Initial proposal presented",
    entities: "Energy Ministry",
    entitiesOther: "Invest in Canada",
    status: "done",
    dueDate: "2024-03-30",
    owner: "Lisa Thompson",
  },
  {
    id: "46",
    country: "ca",
    profileId: "13", // Michael Thompson
    date: "2024-01-20",
    source: "Trade Mission",
    theme: "Trade",
    industry: "Agriculture",
    actionItem: "Increase agricultural exports to Canadian market",
    updates: "Trade barriers assessment completed",
    entities: "Ministry of Agriculture",
    entitiesOther: "Agriculture and Agri-Food Canada",
    status: "in_progress",
    dueDate: "2024-07-25",
    owner: "Robert Johnson",
  },
  {
    id: "47",
    country: "ca",
    profileId: "13", // Michael Thompson
    date: "2024-03-08",
    source: "Summit",
    theme: "Human Capital",
    industry: "Technology",
    actionItem: "Develop tech talent exchange program with Canadian universities",
    updates: "Program parameters defined",
    entities: "Education Ministry",
    entitiesOther: "Universities Canada",
    status: "not_started",
    dueDate: "2024-08-15",
    owner: "Justin Trudeau",
  },
  {
    id: "48",
    country: "ca",
    profileId: "13", // Michael Thompson
    date: "2024-02-15",
    source: "Forum",
    theme: "Knowledge Sharing",
    industry: "Clean Technology",
    actionItem: "Establish knowledge exchange program on clean technology innovation",
    updates: "Priority areas identified",
    entities: "Technology Innovation Center",
    entitiesOther: "National Research Council Canada",
    status: "in_progress",
    dueDate: "2024-06-20",
    owner: "Margaret Wilson",
  }
]

